export type TagDefinitionSeed = {
  id: string;
  code: string;
  name: string;
  type: string;
  subType: string;
  rarityLevel: number;
  styleKey: string;
  iconKey: string;
  sourceType: string;
  isRedeemable: boolean;
  isWearable: boolean;
  isActive: boolean;
  displayPriority: number;
  credibilityWeight: number;
  isAuthoritative: boolean;
  sceneScope: string[];
  description: string;
};

export type PointsGoodsSeed = {
  id: string;
  type: number;
  tagId: string;
  goodsName: string;
  points: number;
  image: string;
  description: string;
  rules: string;
  rarityLevel: number;
  stock: number;
  isAvailable: boolean;
};

export const TAG_DEFINITION_SEEDS: TagDefinitionSeed[] = [
  {
    id: 'tag_identity_angler',
    code: 'identity_angler',
    name: '钓鱼人',
    type: 'identity',
    subType: 'general',
    rarityLevel: 1,
    styleKey: 'identity_slate',
    iconKey: 'fish',
    sourceType: 'system',
    isRedeemable: true,
    isWearable: true,
    isActive: true,
    displayPriority: 80,
    credibilityWeight: 50,
    isAuthoritative: true,
    sceneScope: ['recommend', 'experience', 'question', 'catch', 'trip'],
    description: '基础身份标签，默认授予给新用户。',
  },
  {
    id: 'tag_fun_onlooker',
    code: 'fun_onlooker',
    name: '围观群众',
    type: 'fun',
    subType: 'social',
    rarityLevel: 1,
    styleKey: 'fun_slate',
    iconKey: 'spark',
    sourceType: 'system',
    isRedeemable: true,
    isWearable: true,
    isActive: true,
    displayPriority: 40,
    credibilityWeight: 5,
    isAuthoritative: false,
    sceneScope: ['question', 'catch'],
    description: '轻松的社区氛围标签，新用户默认获得。',
  },
  {
    id: 'tag_identity_want_rod',
    code: 'identity_want_rod',
    name: '想买鱼竿',
    type: 'identity',
    subType: 'gear',
    rarityLevel: 2,
    styleKey: 'identity_slate',
    iconKey: 'rod',
    sourceType: 'shop',
    isRedeemable: true,
    isWearable: true,
    isActive: true,
    displayPriority: 52,
    credibilityWeight: 20,
    isAuthoritative: false,
    sceneScope: ['question', 'recommend'],
    description: '表达当前正在看竿子、做功课的身份倾向。',
  },
  {
    id: 'tag_identity_want_reel',
    code: 'identity_want_reel',
    name: '想买渔轮',
    type: 'identity',
    subType: 'gear',
    rarityLevel: 2,
    styleKey: 'identity_slate',
    iconKey: 'reel',
    sourceType: 'shop',
    isRedeemable: true,
    isWearable: true,
    isActive: true,
    displayPriority: 52,
    credibilityWeight: 20,
    isAuthoritative: false,
    sceneScope: ['question', 'recommend'],
    description: '表达当前正在看轮子、做功课的身份倾向。',
  },
  {
    id: 'tag_fun_almost_skunk',
    code: 'fun_almost_skunk',
    name: '差点打龟',
    type: 'fun',
    subType: 'meme',
    rarityLevel: 2,
    styleKey: 'fun_blue',
    iconKey: 'splash',
    sourceType: 'shop',
    isRedeemable: true,
    isWearable: true,
    isActive: true,
    displayPriority: 38,
    credibilityWeight: 0,
    isAuthoritative: false,
    sceneScope: ['catch', 'trip'],
    description: '轻度翻车也能优雅自嘲的社区梗标签。',
  },
  {
    id: 'tag_fun_empty_hook',
    code: 'fun_empty_hook',
    name: '空钩上鱼',
    type: 'fun',
    subType: 'meme',
    rarityLevel: 2,
    styleKey: 'fun_blue',
    iconKey: 'hook',
    sourceType: 'shop',
    isRedeemable: true,
    isWearable: true,
    isActive: true,
    displayPriority: 36,
    credibilityWeight: 0,
    isAuthoritative: false,
    sceneScope: ['catch'],
    description: '离谱好运时刻专属的趣味标签。',
  },
  {
    id: 'tag_fun_pat_leg',
    code: 'fun_pat_leg',
    name: '拍大腿',
    type: 'fun',
    subType: 'meme',
    rarityLevel: 3,
    styleKey: 'fun_orange',
    iconKey: 'spark',
    sourceType: 'shop',
    isRedeemable: true,
    isWearable: true,
    isActive: true,
    displayPriority: 34,
    credibilityWeight: 0,
    isAuthoritative: false,
    sceneScope: ['question', 'catch', 'trip'],
    description: '错过窗口期后的标准动作标签。',
  },
  {
    id: 'tag_fun_poisoned',
    code: 'fun_poisoned',
    name: '跑过毒',
    type: 'fun',
    subType: 'meme',
    rarityLevel: 3,
    styleKey: 'fun_orange',
    iconKey: 'bolt',
    sourceType: 'shop',
    isRedeemable: true,
    isWearable: true,
    isActive: true,
    displayPriority: 34,
    credibilityWeight: 0,
    isAuthoritative: false,
    sceneScope: ['recommend', 'question'],
    description: '看一眼装备就上头，适合高浓度器材党。',
  },
  {
    id: 'tag_event_founder',
    code: 'event_founder',
    name: '开服元老',
    type: 'event',
    subType: 'founder',
    rarityLevel: 4,
    styleKey: 'official_gold',
    iconKey: 'crown',
    sourceType: 'event',
    isRedeemable: true,
    isWearable: true,
    isActive: true,
    displayPriority: 90,
    credibilityWeight: 60,
    isAuthoritative: true,
    sceneScope: ['experience', 'trip'],
    description: '首批用户纪念标签。',
  },
];

export const POINTS_GOODS_SEEDS: PointsGoodsSeed[] = [
  {
    id: 'goods_tag_identity_want_rod',
    type: 0,
    tagId: 'tag_identity_want_rod',
    goodsName: '想买鱼竿',
    points: 55,
    image: '/images/icons/h28.png',
    description: '器材党入门身份标签，适合把最近的目标挂在主页上。',
    rules: '兑换后永久获得，可在编辑资料中佩戴。',
    rarityLevel: 2,
    stock: 999,
    isAvailable: true,
  },
  {
    id: 'goods_tag_identity_want_reel',
    type: 0,
    tagId: 'tag_identity_want_reel',
    goodsName: '想买渔轮',
    points: 55,
    image: '/images/icons/h28.png',
    description: '器材党入门身份标签，适合把最近的目标挂在主页上。',
    rules: '兑换后永久获得，可在编辑资料中佩戴。',
    rarityLevel: 2,
    stock: 999,
    isAvailable: true,
  },
  {
    id: 'goods_tag_fun_almost_skunk',
    type: 0,
    tagId: 'tag_fun_almost_skunk',
    goodsName: '差点打龟',
    points: 65,
    image: '/images/icons/h28.png',
    description: '轻度翻车也能优雅自嘲的社区梗标签。',
    rules: '兑换后永久获得，可在编辑资料中佩戴。',
    rarityLevel: 2,
    stock: 999,
    isAvailable: true,
  },
  {
    id: 'goods_tag_fun_empty_hook',
    type: 0,
    tagId: 'tag_fun_empty_hook',
    goodsName: '空钩上鱼',
    points: 65,
    image: '/images/icons/h28.png',
    description: '玄学时刻专属，适合把离谱好运写在脸上。',
    rules: '兑换后永久获得，可在编辑资料中佩戴。',
    rarityLevel: 2,
    stock: 999,
    isAvailable: true,
  },
  {
    id: 'goods_tag_fun_pat_leg',
    type: 0,
    tagId: 'tag_fun_pat_leg',
    goodsName: '拍大腿',
    points: 85,
    image: '/images/icons/h31.png',
    description: '错过窗口期后的标准动作，懂的人自然会笑。',
    rules: '兑换后永久获得，可在编辑资料中佩戴。',
    rarityLevel: 3,
    stock: 300,
    isAvailable: true,
  },
  {
    id: 'goods_tag_fun_poisoned',
    type: 0,
    tagId: 'tag_fun_poisoned',
    goodsName: '跑过毒',
    points: 85,
    image: '/images/icons/h31.png',
    description: '看一眼装备就上头，适合高浓度器材党。',
    rules: '兑换后永久获得，可在编辑资料中佩戴。',
    rarityLevel: 3,
    stock: 300,
    isAvailable: true,
  },
  {
    id: 'goods_tag_event_founder',
    type: 0,
    tagId: 'tag_event_founder',
    goodsName: '开服元老',
    points: 100,
    image: '/images/icons/h33.png',
    description: '限量纪念标签，适合首批老用户佩戴。',
    rules: '限量兑换，兑完即止；兑换后永久获得。',
    rarityLevel: 4,
    stock: 50,
    isAvailable: true,
  },
];

export const STARTER_TAG_IDS = ['tag_identity_angler', 'tag_fun_onlooker'];
