const BRAND_IDS = {
    SHIMANO: 1,
    DAIWA: 2,
    ABU_GARCIA: 3,
    LUREFANS: 4,
    '鸦语': 5,
    O_S_P: 6,
    MEGABASS: 7,
    _13_FISHING: 8,
    ACCURATE: 9,
    AFTCO: 10,
    BERKLEY: 11,
    COLUMBIA_PFG: 12,
    DEPS: 13,
    DUO: 14,
    EVERGREEN: 15,
    'Fox Rage / Fox': 16,
    'Frog / Toy Machine': 17,
    FXR: 18,
    GAMAKATSU: 19,
    GAN_CRAFT: 20,
    GARY_YAMAMOTO: 21,
    GILL: 22,
    'Grundéns': 23,
    HUERCO: 24,
    HUK: 25,
    IMA: 26,
    IMAKATSU: 27,
    'Ism / Infinite Blade': 28,
    ISUZU: 29,
    JA_DO: 30,
    JACKALL: 31,
    JACKSON: 32,
    K_T_F: 33,
    KAWA: 34,
    KEITECH: 35,
    LEGIT_DESIGN: 36,
    'Lew’s': 37,
    LUCKY_CRAFT: 38,
    MAJOR_CRAFT: 39,
    MIBRO: 40,
    MUSTO: 41,
    N_S: 42,
    NOIKE: 43,
    NORIES: 44,
    OKUMA: 45,
    OWNER: 46,
    'palms / 小椰树': 47,
    PATAGONIA: 48,
    PELAGIC: 49,
    PENN: 50,
    PHAT_LAB: 51,
    PISCIFUN: 52,
    POWER_PRO: 53,
    RAID_JAPAN: 54,
    RAPALA: 55,
    RIPPLE_FISHER: 56,
    ROMANMADE: 57,
    SEAGUAR: 58,
    SEDITION: 59,
    SIMMS: 60,
    SMITH_LTD: 61,
    'Studio Composite / I.D.': 62,
    SUFIX: 63,
    TAILWALK: 64,
    'Taper & Shape': 65,
    TENRYU: 66,
    'Tiemco / Fenwick': 67,
    TULALA: 68,
    VAGABOND: 69,
    'Valley Hill/Mission Tackle': 70,
    VAN_STAAL: 71,
    VARIVAS: 72,
    WHIPLASH_FACTORY: 73,
    YAMAGA_BLANKS: 74,
    YGK: 75,
    'Yo-Zuri / Duel': 76,
    ZENAQ: 77,
    ZIPBAITS: 78,
    ZPI: 79,
    '东丽 Toray': 80,
    '光威': 81,
    '凯霖': 82,
    '北溟鱼': 83,
    '卡斯丁': 84,
    '品钓': 85,
    '哈斯达': 86,
    '喜曼多 SIMAGO': 87,
    '国王路亚': 88,
    '宝飞龙': 89,
    '巨帝': 90,
    '摩利根 Morigen': 91,
    '桑濑 Sunline': 92,
    '汉鼎': 93,
    '海伯': 94,
    '海龙王': 95,
    '熊王': 96,
    '爱克飞丝 AKFS': 97,
    '盛河': 98,
    '科尼': 99,
    '美人鱼': 100,
    '美夏 EWE': 101,
    '翠鸟': 102,
    '蓝旗鱼': 103,
    '路亚发烧友': 104,
    '钓之屋': 105,
    '钓邦': 106,
    '钓鱼王': 107,
    '领峰': 108,
    '飞蚂蚁': 109,
    '高森 Gosen': 110,
    'BKK': 111,
    OLYMPIC: 113,
    DSTYLE: 114,
    ARK: 115,
    'Gary Yamamoto': 21,
};

const SHEET_NAMES = {
    reel: 'reel',
    spinningReelDetail: 'spinning_reel_detail',
    baitcastingReelDetail: 'baitcasting_reel_detail',
    rod: 'rod',
    rodDetail: 'rod_detail',
    lure: 'lure',
    hardbaitLureDetail: 'hardbait_lure_detail',
    metalLureDetail: 'metal_lure_detail',
    softLureDetail: 'soft_lure_detail',
    wireLureDetail: 'wire_lure_detail',
    jigLureDetail: 'jig_lure_detail',
    line: 'line',
    lineDetail: 'line_detail',
    hook: 'hook',
    hookDetail: 'hook_detail',
};

const HEADERS = {
    reelMaster: [
        'id', 'brand_id', 'model', 'model_cn', 'model_year', 'alias',
        'type_tips', 'type', 'images', 'created_at', 'updated_at',
        'series_positioning', 'main_selling_points', 'official_reference_price', 'market_status',
        'Description', 'market_reference_price', 'player_positioning', 'player_selling_points',
    ],
    spinningReelDetail: [
        'id', 'reel_id', 'SKU', 'GEAR RATIO', 'DRAG', 'MAX DRAG', 'WEIGHT',
        'spool_diameter_per_turn_mm', 'spool_diameter_mm', 'Nylon_no_m', 'Nylon_lb_m', 'fluorocarbon_no_m',
        'fluorocarbon_lb_m', 'pe_no_m', 'cm_per_turn', 'handle_length_mm', 'bearing_count_roller',
        'body_material', 'body_material_tech', 'gear_material', 'handle_knob_type', 'official_environment',
        'line_capacity_display', 'market_reference_price', 'product_code', 'created_at', 'updated_at',
        'drag_click', 'spool_depth_normalized', 'gear_ratio_normalized', 'brake_type_normalized',
        'fit_style_tags', 'min_lure_weight_hint', 'is_compact_body', 'handle_style',
        'MAX_DURABILITY', 'type', 'is_sw_edition', 'variant_description', 'Description',
        'player_environment', 'is_handle_double', 'EV_link', 'Specs_link',
    ],
    baitcastingReelDetail: [
        'id', 'reel_id', 'SKU', 'GEAR RATIO', 'MAX DRAG', 'WEIGHT',
        'spool_diameter_per_turn_mm', 'Nylon_lb_m', 'fluorocarbon_lb_m', 'pe_no_m',
        'cm_per_turn', 'handle_length_mm', 'bearing_count_roller',
        'market_reference_price', 'product_code', 'created_at', 'updated_at',
        'spool_diameter_mm', 'spool_width_mm', 'spool_weight_g', 'handle_knob_type',
        'handle_knob_exchange_size', 'body_material', 'gear_material',
        'battery_capacity', 'battery_charge_time', 'continuous_cast_count',
        'usage_environment', 'DRAG', 'Nylon_no_m', 'fluorocarbon_no_m',
        'drag_click', 'spool_depth_normalized', 'gear_ratio_normalized',
        'brake_type_normalized', 'fit_style_tags', 'min_lure_weight_hint',
        'is_compact_body', 'handle_style', 'MAX_DURABILITY', 'type',
        'EV_link', 'Specs_link',
    ],
    rodMaster: [
        'id', 'brand_id', 'model', 'model_cn', 'model_year', 'alias',
        'type_tips', 'fit_style_tags', 'images', 'created_at', 'updated_at',
        'series_positioning', 'main_selling_points', 'official_reference_price', 'market_status',
        'Description', 'player_positioning', 'player_selling_points',
    ],
    rodDetail: [
        'id', 'rod_id', 'TYPE', 'SKU', 'POWER', 'TOTAL LENGTH', 'Action', 'PIECES',
        'CLOSELENGTH', 'WEIGHT', 'Tip Diameter', 'LURE WEIGHT', 'Line Wt N F',
        'PE Line Size', 'Handle Length', 'Reel Seat Position', 'CONTENT CARBON',
        'Market Reference Price', 'AdminCode', 'Service Card', ' Jig Weight',
        'Squid Jig Size', 'Sinker Rating', 'created_at', 'updated_at',
        'LURE WEIGHT (oz)', 'Sale Price', 'Joint Type', 'Code Name', 'Fly Line',
        'Grip Type', 'Reel Size',
        'guide_layout_type', 'guide_use_hint', 'recommended_rig_pairing', 'hook_keeper_included', 'sweet_spot_lure_weight_real',
        'official_environment', 'player_environment', 'player_positioning', 'player_selling_points',
        'Description', 'Extra Spec 1', 'Extra Spec 2',
    ],
    lureMaster: [
        'id', 'brand_id', 'model', 'model_cn', 'model_year', 'alias',
        'type_tips', 'system', 'water_column', 'action', 'images', 'created_at', 'updated_at', 'description',
    ],
    hardbaitLureDetail: [
        'id', 'lure_id', 'SKU', 'WEIGHT', 'length', 'size', 'sinkingspeed', 'referenceprice',
        'created_at', 'updated_at', 'COLOR', 'AdminCode', 'hook_size', 'depth', 'action', 'subname', 'other.1',
    ],
    metalLureDetail: [
        'id', 'lure_id', 'SKU', 'WEIGHT', 'length', 'size', 'sinkingspeed', 'referenceprice',
        'created_at', 'updated_at', 'COLOR', 'AdminCode', 'hook_size',
    ],
    softLureDetail: [
        'id', 'lure_id', 'SKU', 'WEIGHT', 'length', 'size', 'sinkingspeed', 'referenceprice',
        'created_at', 'updated_at', 'COLOR', 'AdminCode', 'hook_size', 'depth', 'action', 'subname', 'other.1', 'quantity (入数)',
    ],
    wireLureDetail: [
        'id', 'lure_id', 'SKU', 'WEIGHT', 'length', 'size', 'sinkingspeed', 'referenceprice',
        'created_at', 'updated_at', 'COLOR', 'AdminCode', 'hook_size', 'depth', 'action', 'subname', 'other.1',
    ],
    jigLureDetail: [
        'id', 'lure_id', 'SKU', 'WEIGHT', 'length', 'size', 'sinkingspeed', 'referenceprice',
        'created_at', 'updated_at', 'COLOR', 'AdminCode', 'hook_size', 'depth', 'action', 'subname', 'other.1',
    ],
    lineMaster: [
        'id', 'brand_id', 'model', 'model_cn', 'model_year', 'alias',
        'type_tips', 'images', 'created_at', 'updated_at', 'description',
    ],
    lineDetail: [
        'id', 'line_id', 'SKU', 'COLOR', 'LENGTH(m)', 'SIZE NO.', 'MAX STRENGTH(lb)',
        'MAX STRENGTH(kg)', 'AVG STRENGTH(lb)', 'AVG STRENGTH(kg)', 'Market Reference Price',
        'AdminCode', 'created_at', 'updated_at',
    ],
    hookMaster: [
        'id', 'brand_id', 'model', 'model_cn', 'model_year', 'alias',
        'type_tips', 'images', 'created_at', 'updated_at', 'description',
    ],
    hookDetail: [
        'id', 'hookId', 'brand', 'sku', 'type', 'subType', 'gapWidth', 'coating',
        'size', 'quantityPerPack', 'price', 'status', 'description',
    ],
};

module.exports = {
    BRAND_IDS,
    SHEET_NAMES,
    HEADERS,
};
