import { SelectionBranchRule } from '../recommend.types';

export const ROD_SELECTION_BRANCHES: SelectionBranchRule[] = [
  {
    branchKey: 'softbait_focus',
    branchTitle: '专注软饵',
    branchSummary: '更重视底感、轻量和细腻操作。',
    preferredTechniques: ['softbait', '软饵', '铅头钩', '德州', '倒钓'],
    preferredTraits: ['底感', '轻量', '精细', '软饵', '灵敏'],
    budgetMode: 'normal',
    scoring: {
      techniqueMatch: 30,
      powerMatch: 20,
      budgetMatch: 20,
      traitMatch: 15,
      dataCompleteness: 15,
    },
    tradeOffs: ['硬饵远投和大范围搜索不是最优先。'],
  },
  {
    branchKey: 'hardbait_focus',
    branchTitle: '专注硬饵',
    branchSummary: '更适合米诺、铅笔、小胖子等搜索型硬饵。',
    preferredTechniques: ['hardbait', '硬饵', '米诺', '小胖子', '铅笔'],
    preferredTraits: ['硬饵', '搜索', '远投', '控饵', '泛用'],
    budgetMode: 'normal',
    scoring: {
      techniqueMatch: 30,
      powerMatch: 20,
      budgetMatch: 20,
      traitMatch: 15,
      dataCompleteness: 15,
    },
    tradeOffs: ['软饵细腻底感不一定是最强项。'],
  },
  {
    branchKey: 'allround_light',
    branchTitle: '泛用轻量',
    branchSummary: '适合暂时不确定玩法，先买一根覆盖面更大的竿。',
    preferredTechniques: ['unknown', '不确定', '泛用', '软饵', '硬饵'],
    preferredTraits: ['泛用', '轻量', '覆盖', '入门', '全能'],
    budgetMode: 'normal',
    scoring: {
      techniqueMatch: 20,
      powerMatch: 20,
      budgetMatch: 20,
      traitMatch: 25,
      dataCompleteness: 15,
    },
    tradeOffs: ['不是某一种玩法的极致选择。'],
  },
  {
    branchKey: 'durable',
    branchTitle: '结实耐用',
    branchSummary: '优先考虑容错、耐用和新手使用安全感。',
    preferredTechniques: ['泛用', 'unknown', '不确定'],
    preferredTraits: ['耐用', '结实', '容错', '新手', '稳定'],
    budgetMode: 'normal',
    scoring: {
      techniqueMatch: 15,
      powerMatch: 20,
      budgetMatch: 20,
      traitMatch: 30,
      dataCompleteness: 15,
    },
    tradeOffs: ['重量、手感细腻度可能不是最优先。'],
  },
  {
    branchKey: 'budget_down',
    branchTitle: '预算收紧',
    branchSummary: '如果想压预算，优先找参数接近、口碑稳定的低一档系列。',
    preferredTechniques: ['泛用', 'unknown', '不确定'],
    preferredTraits: ['性价比', '入门', '稳定', '预算'],
    budgetMode: 'down',
    scoring: {
      techniqueMatch: 15,
      powerMatch: 20,
      budgetMatch: 35,
      traitMatch: 15,
      dataCompleteness: 15,
    },
    tradeOffs: ['预算更稳，但长期升级空间可能有限。'],
  },
  {
    branchKey: 'budget_up',
    branchTitle: '提预算一步到位',
    branchSummary: '如果能上浮预算，优先看更轻、更细腻、更有长期使用价值的系列。',
    preferredTechniques: ['泛用', '软饵', '硬饵', 'unknown', '不确定'],
    preferredTraits: ['进阶', '轻量', '灵敏', '长期', '高阶'],
    budgetMode: 'up',
    scoring: {
      techniqueMatch: 15,
      powerMatch: 20,
      budgetMatch: 35,
      traitMatch: 15,
      dataCompleteness: 15,
    },
    tradeOffs: ['需要确认预算上浮后是否真的能带来可感知提升。'],
  },
];

